global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer"
    static_configs:
      - targets: ["orderer.example.com:9443"]
  - job_name: "peer0_org1"
    static_configs:
      - targets: ["peer0.org1.example.com:9444"]
  - job_name: "peer0_org2"
    static_configs:
      - targets: ["peer0.org2.example.com:9445"]
  - job_name: "peer0_org3"
    static_configs:
      - targets: ["peer0.org3.example.com:9446"]
  - job_name: "peer0_org4"
    static_configs:
      - targets: ["peer0.org4.example.com:9447"]
  - job_name: "peer0_org5"
    static_configs:
      - targets: ["peer0.org5.example.com:9448"]
  - job_name: "peer0_org6"
    static_configs:
      - targets: ["peer0.org6.example.com:9449"]
  - job_name: "peer0_org7"
    static_configs:
      - targets: ["peer0.org7.example.com:9450"]
  - job_name: "peer0_org8"
    static_configs:
      - targets: ["peer0.org8.example.com:9451"]
  - job_name: "peer0_org9"
    static_configs:
      - targets: ["peer0.org9.example.com:9452"]
  - job_name: "peer0_org10"
    static_configs:
      - targets: ["peer0.org10.example.com:9453"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
